=begin
#Passage Management API

#Passage's management API to manage your Passage apps and users.

The version of the OpenAPI document: 1
Contact: support@passage.id
Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class PassageUser
    attr_accessor :created_at

    attr_accessor :email

    attr_accessor :email_verified

    # The external ID of the user. Only set if the user was created in a Flex app.
    attr_accessor :external_id

    attr_accessor :id

    attr_accessor :last_login_at

    attr_accessor :login_count

    attr_accessor :phone

    attr_accessor :phone_verified

    attr_accessor :recent_events

    attr_accessor :social_connections

    attr_accessor :status

    attr_accessor :updated_at

    attr_accessor :user_metadata

    attr_accessor :webauthn

    attr_accessor :webauthn_devices

    # List of credential types that have been used for authentication
    attr_accessor :webauthn_types

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'email' => :'email',
        :'email_verified' => :'email_verified',
        :'external_id' => :'external_id',
        :'id' => :'id',
        :'last_login_at' => :'last_login_at',
        :'login_count' => :'login_count',
        :'phone' => :'phone',
        :'phone_verified' => :'phone_verified',
        :'recent_events' => :'recent_events',
        :'social_connections' => :'social_connections',
        :'status' => :'status',
        :'updated_at' => :'updated_at',
        :'user_metadata' => :'user_metadata',
        :'webauthn' => :'webauthn',
        :'webauthn_devices' => :'webauthn_devices',
        :'webauthn_types' => :'webauthn_types'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created_at' => :'Time',
        :'email' => :'String',
        :'email_verified' => :'Boolean',
        :'external_id' => :'String',
        :'id' => :'String',
        :'last_login_at' => :'Time',
        :'login_count' => :'Integer',
        :'phone' => :'String',
        :'phone_verified' => :'Boolean',
        :'recent_events' => :'Array<UserRecentEvent>',
        :'social_connections' => :'UserSocialConnections',
        :'status' => :'UserStatus',
        :'updated_at' => :'Time',
        :'user_metadata' => :'Object',
        :'webauthn' => :'Boolean',
        :'webauthn_devices' => :'Array<WebAuthnDevices>',
        :'webauthn_types' => :'Array<WebAuthnType>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'user_metadata',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PassageUser` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PassageUser`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'email_verified')
        self.email_verified = attributes[:'email_verified']
      else
        self.email_verified = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      else
        self.external_id = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'last_login_at')
        self.last_login_at = attributes[:'last_login_at']
      else
        self.last_login_at = nil
      end

      if attributes.key?(:'login_count')
        self.login_count = attributes[:'login_count']
      else
        self.login_count = nil
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      else
        self.phone = nil
      end

      if attributes.key?(:'phone_verified')
        self.phone_verified = attributes[:'phone_verified']
      else
        self.phone_verified = nil
      end

      if attributes.key?(:'recent_events')
        if (value = attributes[:'recent_events']).is_a?(Array)
          self.recent_events = value
        end
      else
        self.recent_events = nil
      end

      if attributes.key?(:'social_connections')
        self.social_connections = attributes[:'social_connections']
      else
        self.social_connections = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'user_metadata')
        self.user_metadata = attributes[:'user_metadata']
      else
        self.user_metadata = nil
      end

      if attributes.key?(:'webauthn')
        self.webauthn = attributes[:'webauthn']
      else
        self.webauthn = nil
      end

      if attributes.key?(:'webauthn_devices')
        if (value = attributes[:'webauthn_devices']).is_a?(Array)
          self.webauthn_devices = value
        end
      else
        self.webauthn_devices = nil
      end

      if attributes.key?(:'webauthn_types')
        if (value = attributes[:'webauthn_types']).is_a?(Array)
          self.webauthn_types = value
        end
      else
        self.webauthn_types = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @email_verified.nil?
        invalid_properties.push('invalid value for "email_verified", email_verified cannot be nil.')
      end

      if @external_id.nil?
        invalid_properties.push('invalid value for "external_id", external_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @last_login_at.nil?
        invalid_properties.push('invalid value for "last_login_at", last_login_at cannot be nil.')
      end

      if @login_count.nil?
        invalid_properties.push('invalid value for "login_count", login_count cannot be nil.')
      end

      if @phone.nil?
        invalid_properties.push('invalid value for "phone", phone cannot be nil.')
      end

      if @phone_verified.nil?
        invalid_properties.push('invalid value for "phone_verified", phone_verified cannot be nil.')
      end

      if @recent_events.nil?
        invalid_properties.push('invalid value for "recent_events", recent_events cannot be nil.')
      end

      if @social_connections.nil?
        invalid_properties.push('invalid value for "social_connections", social_connections cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @webauthn.nil?
        invalid_properties.push('invalid value for "webauthn", webauthn cannot be nil.')
      end

      if @webauthn_devices.nil?
        invalid_properties.push('invalid value for "webauthn_devices", webauthn_devices cannot be nil.')
      end

      if @webauthn_types.nil?
        invalid_properties.push('invalid value for "webauthn_types", webauthn_types cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @created_at.nil?
      return false if @email.nil?
      return false if @email_verified.nil?
      return false if @external_id.nil?
      return false if @id.nil?
      return false if @last_login_at.nil?
      return false if @login_count.nil?
      return false if @phone.nil?
      return false if @phone_verified.nil?
      return false if @recent_events.nil?
      return false if @social_connections.nil?
      return false if @status.nil?
      return false if @updated_at.nil?
      return false if @webauthn.nil?
      return false if @webauthn_devices.nil?
      return false if @webauthn_types.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] email_verified Value to be assigned
    def email_verified=(email_verified)
      if email_verified.nil?
        fail ArgumentError, 'email_verified cannot be nil'
      end

      @email_verified = email_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] external_id Value to be assigned
    def external_id=(external_id)
      if external_id.nil?
        fail ArgumentError, 'external_id cannot be nil'
      end

      @external_id = external_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] last_login_at Value to be assigned
    def last_login_at=(last_login_at)
      if last_login_at.nil?
        fail ArgumentError, 'last_login_at cannot be nil'
      end

      @last_login_at = last_login_at
    end

    # Custom attribute writer method with validation
    # @param [Object] login_count Value to be assigned
    def login_count=(login_count)
      if login_count.nil?
        fail ArgumentError, 'login_count cannot be nil'
      end

      @login_count = login_count
    end

    # Custom attribute writer method with validation
    # @param [Object] phone Value to be assigned
    def phone=(phone)
      if phone.nil?
        fail ArgumentError, 'phone cannot be nil'
      end

      @phone = phone
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_verified Value to be assigned
    def phone_verified=(phone_verified)
      if phone_verified.nil?
        fail ArgumentError, 'phone_verified cannot be nil'
      end

      @phone_verified = phone_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] recent_events Value to be assigned
    def recent_events=(recent_events)
      if recent_events.nil?
        fail ArgumentError, 'recent_events cannot be nil'
      end

      @recent_events = recent_events
    end

    # Custom attribute writer method with validation
    # @param [Object] social_connections Value to be assigned
    def social_connections=(social_connections)
      if social_connections.nil?
        fail ArgumentError, 'social_connections cannot be nil'
      end

      @social_connections = social_connections
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] webauthn Value to be assigned
    def webauthn=(webauthn)
      if webauthn.nil?
        fail ArgumentError, 'webauthn cannot be nil'
      end

      @webauthn = webauthn
    end

    # Custom attribute writer method with validation
    # @param [Object] webauthn_devices Value to be assigned
    def webauthn_devices=(webauthn_devices)
      if webauthn_devices.nil?
        fail ArgumentError, 'webauthn_devices cannot be nil'
      end

      @webauthn_devices = webauthn_devices
    end

    # Custom attribute writer method with validation
    # @param [Object] webauthn_types Value to be assigned
    def webauthn_types=(webauthn_types)
      if webauthn_types.nil?
        fail ArgumentError, 'webauthn_types cannot be nil'
      end

      @webauthn_types = webauthn_types
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          email == o.email &&
          email_verified == o.email_verified &&
          external_id == o.external_id &&
          id == o.id &&
          last_login_at == o.last_login_at &&
          login_count == o.login_count &&
          phone == o.phone &&
          phone_verified == o.phone_verified &&
          recent_events == o.recent_events &&
          social_connections == o.social_connections &&
          status == o.status &&
          updated_at == o.updated_at &&
          user_metadata == o.user_metadata &&
          webauthn == o.webauthn &&
          webauthn_devices == o.webauthn_devices &&
          webauthn_types == o.webauthn_types
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created_at, email, email_verified, external_id, id, last_login_at, login_count, phone, phone_verified, recent_events, social_connections, status, updated_at, user_metadata, webauthn, webauthn_devices, webauthn_types].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
