AllCops:
  Exclude:
    - 'lib/openapi_client/**/*'
    - 'lib/openapi_client.rb'
    - 'docs/generated/*'

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50
    
Metrics/AbcSize:
  Max: 20
