AllCops:
  Exclude:
    - 'lib/openapi_client/**/*'
    - 'lib/openapi_client.rb'
    - 'lib/models/update_magic_link_auth_method.rb'
    - 'lib/models/update_otp_auth_method.rb'
    - 'lib/models/update_passkeys_auth_method.rb'

Naming/AccessorMethodName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  