=begin
#Passage Management API

#Passage's management API to manage your Passage apps and users.

The version of the OpenAPI document: 1
Contact: support@passage.id
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

module OpenapiClient
  VERSION = '1.0.0'
end
