name: Deploy Ruby Gem

on:
  push:
    branches: [main]

env:
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  PSG_JWT: ${{ secrets.PSG_JWT }}
  TEST_USER_ID: ${{ secrets.TEST_USER_ID }}


jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Run Tests
        run: |
          gem build passageidentity.gemspec -o test.gem
          gem install test.gem
          rm test.gem
          ruby tests/all.rb

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
