name: Lint, Format, and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  PSG_JWT: ${{ secrets.PSG_JWT }}
  TEST_USER_ID: ${{ secrets.TEST_USER_ID }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install Rubocop
      run: gem install rubocop
    - name: Lint
      run: rubocop -l
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install Rubocop
      run: gem install rubocop
    - name: Format
      run: rubocop --format github
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install dependencies
      run: bundle install
    - name: Test
      run: ruby tests/all.rb